### ISSUE TITLE
Command block: execute one-by-one vs entirety

### ISSUE THREAD

**Issue by sourishkrout** [stateful/rdme#10]
I did some testing based on this example: https://github.com/lifeiscontent/realworld

However, since it's not an interactive shell, the directory changes aren't retained across commands. Quick-fix involved concatenating the commands with `;` making them insensitive to non-zero exit codes. Ran into an issue where RoR's migrations failed due to "duplication" which is a red herring.

Perhaps there's a better way to do this?

```
diff --git a/internal/runner/shell.go b/internal/runner/shell.go
index d9967d2..abf3422 100644
--- a/internal/runner/shell.go
+++ b/internal/runner/shell.go
@@ -5,6 +5,7 @@ import (
 	"io"
 	"os"
 	"os/exec"
+	"strings"
 
 	"github.com/pkg/errors"
 )
@@ -20,10 +21,9 @@ func (s Shell) Run(ctx context.Context) error {
 		sh = "/bin/sh"
 	}
 
-	for _, cmd := range s.Cmds {
-		if err := execSingle(ctx, sh, s.Dir, cmd, s.Stdin, s.Stdout, s.Stderr); err != nil {
-			return err
-		}
+	concatCmds := strings.Join(s.Cmds, "; ")
+	if err := execSingle(ctx, sh, s.Dir, concatCmds, s.Stdin, s.Stdout, s.Stderr); err != nil {
+		return err
 	}
 
 	return nil
```

**Comment by sourishkrout** [comment]
Any thoughts on this one @adambabik?

**Comment by adambabik** [comment]
I think we can concatenate it but likely we should set some bash flags so that we fail early instead of continuing if any previous command fail. Overall, it makes sense, we should have an option to run a snippet as a whole.

**Comment by sourishkrout** [comment]
> I think we can concatenate it but likely we should set some bash flags so that we fail early instead of continuing if any previous command fail. Overall, it makes sense, we should have an option to run a snippet as a whole.

I almost want to make it default to run multiple lines (if they are part of  the same block). For bash flags you mean `set -o pipefail` @adambabik?

**Comment by adambabik** [comment]
Makes sense, so I will default to run it as a single command. Regarding flags, yes that's one of them. I think `-x` would also be nice. [Here](https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425) is a nice write up.

**Comment by adambabik** [comment]
Closed in https://github.com/stateful/rdme/pull/17.
